export enum EVENTS {
  SHOW_ALERT = 'SHOW_ALERT',
  SHOW_MODAL = 'SHOW_MODAL',
  HIDE_MODAL = 'HIDE_MODAL',
  AVATAR_UPDATE = 'AVATAR_UPDATE', // 用户在本地选择了新的头像
  SHOW_MODAL_AVATAR = 'SHOW_MODAL_AVATAR', // 打开头像上传弹窗
  SHOW_MODAL_BASE_INFO = 'SHOW_MODAL_BASE_INFO', // 打开基础信息编辑弹窗
  SHOW_MODAL_SOCIAL_LINK = 'SHOW_MODAL_SOCIAL_LINK', // 打开“社交平台图标”弹窗
  SHOW_MODAL_ADD_SOCIAL_LINK = 'SHOW_MODAL_ADD_SOCIAL_LINK', // 打开“添加社交平台图标”弹窗
  SHOW_MODAL_SOCIAL_LINK_ICON = 'SHOW_MODAL_SOCIAL_LINK_ICON' // 打开“添加指定社交平台内容”弹窗
}
