export enum EVENTS {
  SHOW_MODAL = 'SHOW_MODAL',
  HIDE_MODAL = 'HIDE_MODAL',
  AVATAR_UPDATE = 'AVATAR_UPDATE', // 修改头像时，头像有更新
  INTRO_UPDATE = 'INTRO_UPDATE',
  AVATAR_CLICK = 'AVATAR_CLICK',
  USERNAME_INTRO_CLICK = 'USERNAME_INTRO_CLICK',
  SOCIAL_LINK_CLICK = 'SOCIAL_LINK_CLICK',
}
