export enum EVENTS {
  SHOW_MODAL = 'SHOW_MODAL',
  HIDE_MODAL = 'HIDE_MODAL',
  AVATAR_UPDATE = 'AVATAR_UPDATE', // 修改头像时，头像有更新
  USERNAME_UPDATE = 'USERNAME_UPDATE',
  INTRO_UPDATE = 'INTRO_UPDATE',
}
