import { SocialLink, SocialLinks } from '@/app/types/my';

export const SOCIAL_LINKS_TEXT = {
  [SocialLinks.ALI_PAY]: '支付宝',
  [SocialLinks.ALI_WANG_WANG]: '阿里旺旺',
  [SocialLinks.AMAZON]: '亚马逊',
  [SocialLinks.APPLE_APP_STORE]: '苹果应用商店',
  [SocialLinks.APPLE_MUSIC]: '苹果音乐',
  [SocialLinks.APPLE_PODCASTS]: '苹果播客',
  [SocialLinks.ART_STATION]: 'Artstation',
  [SocialLinks.BAI_HE]: '百合网',
  [SocialLinks.BANDCAMP]: 'Bandcamp',
  [SocialLinks.BAO_BAO_SHU]: '宝宝树',
  [SocialLinks.BEHANCE]: 'Behance',
  [SocialLinks.BILI_BILI]: ' B站',
  [SocialLinks.BLUE_SKY]: 'Bluesky',
  [SocialLinks.BOSS]: 'Boss 直聘',
  [SocialLinks.CAMEO]: 'Cameo',
  [SocialLinks.CLUB_HOUSE]: 'Clubhouse',
  [SocialLinks.DING_TALK]: '钉钉',
  [SocialLinks.DISCORD]: 'Discord',
  [SocialLinks.DOU_BAN]: '豆瓣',
  [SocialLinks.DOU_YIN]: '抖音',
  [SocialLinks.DRIBBLE]: 'Dribble',
  [SocialLinks.DROPBOX]: 'Dropbox',
  [SocialLinks.DUO_LIN_GUO]: '多邻国',
  [SocialLinks.EMAIL]: '电子邮箱',
  [SocialLinks.ESTY]: 'Esty',
  [SocialLinks.FACEBOOK]: 'Facebook',
  [SocialLinks.FEI_SHU]: '飞书',
  [SocialLinks.GITHUB]: 'Github',
  [SocialLinks.GITLAB]: 'Gitlab',
  [SocialLinks.GOOD_READS]: 'Goodreads',
  [SocialLinks.GOOGLE_PLAY_STORE]: '谷歌应用商店',
  [SocialLinks.GOOGLE_PODCAST]: '谷歌播客',
  [SocialLinks.HU_PU]: '虎扑',
  [SocialLinks.INSTAGRAM]: 'Instagram',
  [SocialLinks.JD]: '京东',
  [SocialLinks.SHI_JI_JIA_YUAN]: '世纪佳缘',
  [SocialLinks.JUE_JIN]: '稀土掘金',
  [SocialLinks.KICK]: 'Kick',
  [SocialLinks.KUAI_SHOU]: '快手',
  [SocialLinks.LA_GOU]: '拉勾',
  [SocialLinks.LAST_FM]: 'Last.fm',
  [SocialLinks.LINKED_IN]: '领英',
  [SocialLinks.LOFTER]: 'LOFTER',
  [SocialLinks.MA_FENG_WO]: '马蜂窝',
  [SocialLinks.MAI_MAI]: '脉脉',
  [SocialLinks.MASTONDON]: 'Mastondon',
  [SocialLinks.MEDIUM]: 'Medium',
  [SocialLinks.MEET_UP]: 'Meetup',
  [SocialLinks.MO_MO]: '沫沫',
  [SocialLinks.ONLY_FANS]: 'Onlyfans',
  [SocialLinks.PATREON]: 'Patreon',
  [SocialLinks.PDD]: '拼多多',
  [SocialLinks.PHONE]: '电话',
  [SocialLinks.PINTREST]: 'Pintrest',
  [SocialLinks.POSH_MARK]: 'Poshmark',
  [SocialLinks.QIN_BAO_BAO]: '亲宝宝',
  [SocialLinks.QQ]: 'QQ',
  [SocialLinks.REDDIT]: 'Reddit',
  [SocialLinks.SIGNAL]: 'Signal',
  [SocialLinks.SKYPE]: 'Skype',
  [SocialLinks.SLACK]: 'Slack',
  [SocialLinks.SNAPCHAT]: 'Snapchat',
  [SocialLinks.SOUL]: 'Soul',
  [SocialLinks.SOUND_CLOUD]: 'Soundcloud',
  [SocialLinks.SPOTIFY]: 'Spotify',
  [SocialLinks.SUBSTACK]: 'Substack',
  [SocialLinks.TANG_DOU]: '糖豆',
  [SocialLinks.TAN_TAN]: '探探',
  [SocialLinks.TAO_BAO]: '淘宝',
  [SocialLinks.TELEGRAM]: 'Telegram',
  [SocialLinks.THREADS]: 'Threads',
  [SocialLinks.TIKTOK]: 'Tiktok',
  [SocialLinks.TUMBLR]: 'Tumblr',
  [SocialLinks.TWITCH]: 'Twitch',
  [SocialLinks.UNSPLASH]: 'Unsplash',
  [SocialLinks.VENMO]: 'Venmo',
  [SocialLinks.VIMEO]: 'Vimeo',
  [SocialLinks.WE_COM]: '企业微信',
  [SocialLinks.WEBSITE]: '网址',
  [SocialLinks.WECHAT]: '微信',
  [SocialLinks.WEI_BO]: '微博',
  [SocialLinks.WHATSAPP]: 'WhatsApp',
  [SocialLinks.X]: 'X(Twitter)',
  [SocialLinks.XIAN_YU]: '闲鱼',
  [SocialLinks.XIAO_HONG_SHU]: '小红书',
  [SocialLinks.XUE_QIU]: '雪球',
  [SocialLinks.YOUTUBE]: 'Youtube',
  [SocialLinks.ZHI_HU]: '知乎',
} as const;

export const LIST_SOCIAL_LINKS: SocialLink[] = [
  {
    id: SocialLinks.ALI_PAY,
    name: SOCIAL_LINKS_TEXT[SocialLinks.ALI_PAY],
    icon: SocialLinks.ALI_PAY,
  },
  {
    id: SocialLinks.ALI_WANG_WANG,
    name: SOCIAL_LINKS_TEXT[SocialLinks.ALI_WANG_WANG],
    icon: SocialLinks.ALI_WANG_WANG,
  },
  {
    id: SocialLinks.AMAZON,
    name: SOCIAL_LINKS_TEXT[SocialLinks.AMAZON],
    icon: SocialLinks.AMAZON,
  },
  {
    id: SocialLinks.APPLE_APP_STORE,
    name: SOCIAL_LINKS_TEXT[SocialLinks.APPLE_APP_STORE],
    icon: SocialLinks.APPLE_APP_STORE,
  },
  {
    id: SocialLinks.APPLE_MUSIC,
    name: SOCIAL_LINKS_TEXT[SocialLinks.APPLE_MUSIC],
    icon: SocialLinks.APPLE_MUSIC,
  },
  {
    id: SocialLinks.APPLE_PODCASTS,
    name: SOCIAL_LINKS_TEXT[SocialLinks.APPLE_PODCASTS],
    icon: SocialLinks.APPLE_PODCASTS,
  },
  {
    id: SocialLinks.ART_STATION,
    name: SOCIAL_LINKS_TEXT[SocialLinks.ART_STATION],
    icon: SocialLinks.ART_STATION,
  },
  {
    id: SocialLinks.BAI_HE,
    name: SOCIAL_LINKS_TEXT[SocialLinks.BAI_HE],
    icon: SocialLinks.BAI_HE,
  },
  {
    id: SocialLinks.BANDCAMP,
    name: SOCIAL_LINKS_TEXT[SocialLinks.BANDCAMP],
    icon: SocialLinks.BANDCAMP,
  },
  {
    id: SocialLinks.BAO_BAO_SHU,
    name: SOCIAL_LINKS_TEXT[SocialLinks.BAO_BAO_SHU],
    icon: SocialLinks.BAO_BAO_SHU,
  },
  {
    id: SocialLinks.BEHANCE,
    name: SOCIAL_LINKS_TEXT[SocialLinks.BEHANCE],
    icon: SocialLinks.BEHANCE,
  },
  {
    id: SocialLinks.BILI_BILI,
    name: SOCIAL_LINKS_TEXT[SocialLinks.BILI_BILI],
    icon: SocialLinks.BILI_BILI,
  },
  {
    id: SocialLinks.BLUE_SKY,
    name: SOCIAL_LINKS_TEXT[SocialLinks.BLUE_SKY],
    icon: SocialLinks.BLUE_SKY,
  },
  {
    id: SocialLinks.BOSS,
    name: SOCIAL_LINKS_TEXT[SocialLinks.BOSS],
    icon: SocialLinks.BOSS,
  },
  {
    id: SocialLinks.CAMEO,
    name: SOCIAL_LINKS_TEXT[SocialLinks.CAMEO],
    icon: SocialLinks.CAMEO,
  },
  {
    id: SocialLinks.CLUB_HOUSE,
    name: SOCIAL_LINKS_TEXT[SocialLinks.CLUB_HOUSE],
    icon: SocialLinks.CLUB_HOUSE,
  },
  {
    id: SocialLinks.DING_TALK,
    name: SOCIAL_LINKS_TEXT[SocialLinks.DING_TALK],
    icon: SocialLinks.DING_TALK,
  },
  {
    id: SocialLinks.DISCORD,
    name: SOCIAL_LINKS_TEXT[SocialLinks.DISCORD],
    icon: SocialLinks.DISCORD,
  },
  {
    id: SocialLinks.DOU_BAN,
    name: SOCIAL_LINKS_TEXT[SocialLinks.DOU_BAN],
    icon: SocialLinks.DOU_BAN,
  },
  {
    id: SocialLinks.DOU_YIN,
    name: SOCIAL_LINKS_TEXT[SocialLinks.DOU_YIN],
    icon: SocialLinks.TIKTOK,
  },
  {
    id: SocialLinks.DRIBBLE,
    name: SOCIAL_LINKS_TEXT[SocialLinks.DRIBBLE],
    icon: SocialLinks.DRIBBLE,
  },
  {
    id: SocialLinks.DROPBOX,
    name: SOCIAL_LINKS_TEXT[SocialLinks.DROPBOX],
    icon: SocialLinks.DROPBOX,
  },
  {
    id: SocialLinks.DUO_LIN_GUO,
    name: SOCIAL_LINKS_TEXT[SocialLinks.DUO_LIN_GUO],
    icon: SocialLinks.DUO_LIN_GUO,
  },
  {
    id: SocialLinks.EMAIL,
    name: SOCIAL_LINKS_TEXT[SocialLinks.EMAIL],
    icon: SocialLinks.EMAIL,
  },
  {
    id: SocialLinks.ESTY,
    name: SOCIAL_LINKS_TEXT[SocialLinks.ESTY],
    icon: SocialLinks.ESTY,
  },
  {
    id: SocialLinks.FACEBOOK,
    name: SOCIAL_LINKS_TEXT[SocialLinks.FACEBOOK],
    icon: SocialLinks.FACEBOOK,
  },
  {
    id: SocialLinks.FEI_SHU,
    name: SOCIAL_LINKS_TEXT[SocialLinks.FEI_SHU],
    icon: SocialLinks.FEI_SHU,
  },
  {
    id: SocialLinks.GITHUB,
    name: SOCIAL_LINKS_TEXT[SocialLinks.GITHUB],
    icon: SocialLinks.GITHUB,
  },
  {
    id: SocialLinks.GITLAB,
    name: SOCIAL_LINKS_TEXT[SocialLinks.GITLAB],
    icon: SocialLinks.GITLAB,
  },
  {
    id: SocialLinks.GOOD_READS,
    name: SOCIAL_LINKS_TEXT[SocialLinks.GOOD_READS],
    icon: SocialLinks.GOOD_READS,
  },
  {
    id: SocialLinks.GOOGLE_PLAY_STORE,
    name: SOCIAL_LINKS_TEXT[SocialLinks.GOOGLE_PLAY_STORE],
    icon: SocialLinks.GOOGLE_PLAY_STORE,
  },
  {
    id: SocialLinks.GOOGLE_PODCAST,
    name: SOCIAL_LINKS_TEXT[SocialLinks.GOOGLE_PODCAST],
    icon: SocialLinks.GOOGLE_PODCAST,
  },
  {
    id: SocialLinks.HU_PU,
    name: SOCIAL_LINKS_TEXT[SocialLinks.HU_PU],
    icon: SocialLinks.HU_PU,
  },
  {
    id: SocialLinks.INSTAGRAM,
    name: SOCIAL_LINKS_TEXT[SocialLinks.INSTAGRAM],
    icon: SocialLinks.INSTAGRAM,
  },
  {
    id: SocialLinks.JD,
    name: SOCIAL_LINKS_TEXT[SocialLinks.JD],
    icon: SocialLinks.JD,
  },
  {
    id: SocialLinks.SHI_JI_JIA_YUAN,
    name: SOCIAL_LINKS_TEXT[SocialLinks.SHI_JI_JIA_YUAN],
    icon: SocialLinks.SHI_JI_JIA_YUAN,
  },
  {
    id: SocialLinks.JUE_JIN,
    name: SOCIAL_LINKS_TEXT[SocialLinks.JUE_JIN],
    icon: SocialLinks.JUE_JIN,
  },
  {
    id: SocialLinks.KICK,
    name: SOCIAL_LINKS_TEXT[SocialLinks.KICK],
    icon: SocialLinks.KICK,
  },
  {
    id: SocialLinks.KUAI_SHOU,
    name: SOCIAL_LINKS_TEXT[SocialLinks.KUAI_SHOU],
    icon: SocialLinks.KUAI_SHOU,
  },
  {
    id: SocialLinks.LA_GOU,
    name: SOCIAL_LINKS_TEXT[SocialLinks.LA_GOU],
    icon: SocialLinks.LA_GOU,
  },
  {
    id: SocialLinks.LAST_FM,
    name: SOCIAL_LINKS_TEXT[SocialLinks.LAST_FM],
    icon: SocialLinks.LAST_FM,
  },
  {
    id: SocialLinks.LINKED_IN,
    name: SOCIAL_LINKS_TEXT[SocialLinks.LINKED_IN],
    icon: SocialLinks.LINKED_IN,
  },
  {
    id: SocialLinks.LOFTER,
    name: SOCIAL_LINKS_TEXT[SocialLinks.LOFTER],
    icon: SocialLinks.LOFTER,
  },
  {
    id: SocialLinks.MA_FENG_WO,
    name: SOCIAL_LINKS_TEXT[SocialLinks.MA_FENG_WO],
    icon: SocialLinks.MA_FENG_WO,
  },
  {
    id: SocialLinks.MAI_MAI,
    name: SOCIAL_LINKS_TEXT[SocialLinks.MAI_MAI],
    icon: SocialLinks.MAI_MAI,
  },
  {
    id: SocialLinks.MASTONDON,
    name: SOCIAL_LINKS_TEXT[SocialLinks.MASTONDON],
    icon: SocialLinks.MASTONDON,
  },
  {
    id: SocialLinks.MEDIUM,
    name: SOCIAL_LINKS_TEXT[SocialLinks.MEDIUM],
    icon: SocialLinks.MEDIUM,
  },
  {
    id: SocialLinks.MEET_UP,
    name: SOCIAL_LINKS_TEXT[SocialLinks.MEET_UP],
    icon: SocialLinks.MEET_UP,
  },
  {
    id: SocialLinks.MO_MO,
    name: SOCIAL_LINKS_TEXT[SocialLinks.MO_MO],
    icon: SocialLinks.MO_MO,
  },
  {
    id: SocialLinks.ONLY_FANS,
    name: SOCIAL_LINKS_TEXT[SocialLinks.ONLY_FANS],
    icon: SocialLinks.ONLY_FANS,
  },
  {
    id: SocialLinks.PATREON,
    name: SOCIAL_LINKS_TEXT[SocialLinks.PATREON],
    icon: SocialLinks.PATREON,
  },
  {
    id: SocialLinks.PDD,
    name: SOCIAL_LINKS_TEXT[SocialLinks.PDD],
    icon: SocialLinks.PDD,
  },
  {
    id: SocialLinks.PHONE,
    name: SOCIAL_LINKS_TEXT[SocialLinks.PHONE],
    icon: SocialLinks.PHONE,
  },
  {
    id: SocialLinks.PINTREST,
    name: SOCIAL_LINKS_TEXT[SocialLinks.PINTREST],
    icon: SocialLinks.PINTREST,
  },
  {
    id: SocialLinks.POSH_MARK,
    name: SOCIAL_LINKS_TEXT[SocialLinks.POSH_MARK],
    icon: SocialLinks.POSH_MARK,
  },
  {
    id: SocialLinks.QIN_BAO_BAO,
    name: SOCIAL_LINKS_TEXT[SocialLinks.QIN_BAO_BAO],
    icon: SocialLinks.QIN_BAO_BAO,
  },
  {
    id: SocialLinks.QQ,
    name: SOCIAL_LINKS_TEXT[SocialLinks.QQ],
    icon: SocialLinks.QQ,
  },
  {
    id: SocialLinks.REDDIT,
    name: SOCIAL_LINKS_TEXT[SocialLinks.REDDIT],
    icon: SocialLinks.REDDIT,
  },
  {
    id: SocialLinks.SIGNAL,
    name: SOCIAL_LINKS_TEXT[SocialLinks.SIGNAL],
    icon: SocialLinks.SIGNAL,
  },
  {
    id: SocialLinks.SKYPE,
    name: SOCIAL_LINKS_TEXT[SocialLinks.SKYPE],
    icon: SocialLinks.SKYPE,
  },
  {
    id: SocialLinks.SLACK,
    name: SOCIAL_LINKS_TEXT[SocialLinks.SLACK],
    icon: SocialLinks.SLACK,
  },
  {
    id: SocialLinks.SNAPCHAT,
    name: SOCIAL_LINKS_TEXT[SocialLinks.SNAPCHAT],
    icon: SocialLinks.SNAPCHAT,
  },
  {
    id: SocialLinks.SOUL,
    name: SOCIAL_LINKS_TEXT[SocialLinks.SOUL],
    icon: SocialLinks.SOUL,
  },
  {
    id: SocialLinks.SOUND_CLOUD,
    name: SOCIAL_LINKS_TEXT[SocialLinks.SOUND_CLOUD],
    icon: SocialLinks.SOUND_CLOUD,
  },
  {
    id: SocialLinks.SPOTIFY,
    name: SOCIAL_LINKS_TEXT[SocialLinks.SPOTIFY],
    icon: SocialLinks.SPOTIFY,
  },
  {
    id: SocialLinks.SUBSTACK,
    name: SOCIAL_LINKS_TEXT[SocialLinks.SUBSTACK],
    icon: SocialLinks.SUBSTACK,
  },
  {
    id: SocialLinks.TANG_DOU,
    name: SOCIAL_LINKS_TEXT[SocialLinks.TANG_DOU],
    icon: SocialLinks.TANG_DOU,
  },
  {
    id: SocialLinks.TAN_TAN,
    name: SOCIAL_LINKS_TEXT[SocialLinks.TAN_TAN],
    icon: SocialLinks.TAN_TAN,
  },
  {
    id: SocialLinks.TAO_BAO,
    name: SOCIAL_LINKS_TEXT[SocialLinks.TAO_BAO],
    icon: SocialLinks.TAO_BAO,
  },
  {
    id: SocialLinks.TELEGRAM,
    name: SOCIAL_LINKS_TEXT[SocialLinks.TELEGRAM],
    icon: SocialLinks.TELEGRAM,
  },
  {
    id: SocialLinks.THREADS,
    name: SOCIAL_LINKS_TEXT[SocialLinks.THREADS],
    icon: SocialLinks.THREADS,
  },
  {
    id: SocialLinks.TIKTOK,
    name: SOCIAL_LINKS_TEXT[SocialLinks.TIKTOK],
    icon: SocialLinks.TIKTOK,
  },
  {
    id: SocialLinks.TUMBLR,
    name: SOCIAL_LINKS_TEXT[SocialLinks.TUMBLR],
    icon: SocialLinks.TUMBLR,
  },
  {
    id: SocialLinks.TWITCH,
    name: SOCIAL_LINKS_TEXT[SocialLinks.TWITCH],
    icon: SocialLinks.TWITCH,
  },
  {
    id: SocialLinks.UNSPLASH,
    name: SOCIAL_LINKS_TEXT[SocialLinks.UNSPLASH],
    icon: SocialLinks.UNSPLASH,
  },
  {
    id: SocialLinks.VENMO,
    name: SOCIAL_LINKS_TEXT[SocialLinks.VENMO],
    icon: SocialLinks.VENMO,
  },
  {
    id: SocialLinks.VIMEO,
    name: SOCIAL_LINKS_TEXT[SocialLinks.VIMEO],
    icon: SocialLinks.VIMEO,
  },
  {
    id: SocialLinks.WE_COM,
    name: SOCIAL_LINKS_TEXT[SocialLinks.WE_COM],
    icon: SocialLinks.WE_COM,
  },
  {
    id: SocialLinks.WEBSITE,
    name: SOCIAL_LINKS_TEXT[SocialLinks.WEBSITE],
    icon: SocialLinks.WEBSITE,
  },
  {
    id: SocialLinks.WECHAT,
    name: SOCIAL_LINKS_TEXT[SocialLinks.WECHAT],
    icon: SocialLinks.WECHAT,
  },
  {
    id: SocialLinks.WEI_BO,
    name: SOCIAL_LINKS_TEXT[SocialLinks.WEI_BO],
    icon: SocialLinks.WEI_BO,
  },
  {
    id: SocialLinks.WHATSAPP,
    name: SOCIAL_LINKS_TEXT[SocialLinks.WHATSAPP],
    icon: SocialLinks.WHATSAPP,
  },
  {
    id: SocialLinks.X,
    name: SOCIAL_LINKS_TEXT[SocialLinks.X],
    icon: SocialLinks.X,
  },
  {
    id: SocialLinks.XIAN_YU,
    name: SOCIAL_LINKS_TEXT[SocialLinks.XIAN_YU],
    icon: SocialLinks.XIAN_YU,
  },
  {
    id: SocialLinks.XIAO_HONG_SHU,
    name: SOCIAL_LINKS_TEXT[SocialLinks.XIAO_HONG_SHU],
    icon: SocialLinks.XIAO_HONG_SHU,
  },
  {
    id: SocialLinks.XUE_QIU,
    name: SOCIAL_LINKS_TEXT[SocialLinks.XUE_QIU],
    icon: SocialLinks.XUE_QIU,
  },
  {
    id: SocialLinks.YOUTUBE,
    name: SOCIAL_LINKS_TEXT[SocialLinks.YOUTUBE],
    icon: SocialLinks.YOUTUBE,
  },
  {
    id: SocialLinks.ZHI_HU,
    name: SOCIAL_LINKS_TEXT[SocialLinks.ZHI_HU],
    icon: SocialLinks.ZHI_HU,
  },
];

export const DEFAULT_SOCIAL_LINKS = [
  {
    id: SocialLinks.WECHAT,
    name: SOCIAL_LINKS_TEXT[SocialLinks.WECHAT],
    icon: SocialLinks.WECHAT,
  },
  {
    id: SocialLinks.QQ,
    name: SOCIAL_LINKS_TEXT[SocialLinks.QQ],
    icon: SocialLinks.QQ,
  },
  {
    id: SocialLinks.DOU_YIN,
    name: SOCIAL_LINKS_TEXT[SocialLinks.DOU_YIN],
    icon: SocialLinks.TIKTOK,
  },
  {
    id: SocialLinks.PHONE,
    name: SOCIAL_LINKS_TEXT[SocialLinks.PHONE],
    icon: SocialLinks.PHONE,
  }
];
