import { SocialLinkItem, SocialPlatform } from '@/app/types/my';

export const SOCIAL_LINKS_TEXT = {
  [SocialPlatform.ALI_PAY]: '支付宝',
  [SocialPlatform.ALI_WANG_WANG]: '阿里旺旺',
  [SocialPlatform.AMAZON]: '亚马逊',
  [SocialPlatform.APPLE_APP_STORE]: '苹果应用商店',
  [SocialPlatform.APPLE_MUSIC]: '苹果音乐',
  [SocialPlatform.APPLE_PODCASTS]: '苹果播客',
  [SocialPlatform.ART_STATION]: 'Artstation',
  [SocialPlatform.BAI_HE]: '百合网',
  [SocialPlatform.BANDCAMP]: 'Bandcamp',
  [SocialPlatform.BAO_BAO_SHU]: '宝宝树',
  [SocialPlatform.BEHANCE]: 'Behance',
  [SocialPlatform.BILI_BILI]: ' B站',
  [SocialPlatform.BLUE_SKY]: 'Bluesky',
  [SocialPlatform.BOSS]: 'Boss 直聘',
  [SocialPlatform.CAMEO]: 'Cameo',
  [SocialPlatform.CLUB_HOUSE]: 'Clubhouse',
  [SocialPlatform.DING_TALK]: '钉钉',
  [SocialPlatform.DISCORD]: 'Discord',
  [SocialPlatform.DOU_BAN]: '豆瓣',
  [SocialPlatform.DOU_YIN]: '抖音',
  [SocialPlatform.DRIBBLE]: 'Dribble',
  [SocialPlatform.DROPBOX]: 'Dropbox',
  [SocialPlatform.DUO_LIN_GUO]: '多邻国',
  [SocialPlatform.EMAIL]: '电子邮箱',
  [SocialPlatform.ESTY]: 'Esty',
  [SocialPlatform.FACEBOOK]: 'Facebook',
  [SocialPlatform.FEI_SHU]: '飞书',
  [SocialPlatform.GITHUB]: 'Github',
  [SocialPlatform.GITLAB]: 'Gitlab',
  [SocialPlatform.GOOD_READS]: 'Goodreads',
  [SocialPlatform.GOOGLE_PLAY_STORE]: '谷歌应用商店',
  [SocialPlatform.GOOGLE_PODCAST]: '谷歌播客',
  [SocialPlatform.HU_PU]: '虎扑',
  [SocialPlatform.INSTAGRAM]: 'Instagram',
  [SocialPlatform.JD]: '京东',
  [SocialPlatform.SHI_JI_JIA_YUAN]: '世纪佳缘',
  [SocialPlatform.JUE_JIN]: '稀土掘金',
  [SocialPlatform.KICK]: 'Kick',
  [SocialPlatform.KUAI_SHOU]: '快手',
  [SocialPlatform.LA_GOU]: '拉勾',
  [SocialPlatform.LAST_FM]: 'Last.fm',
  [SocialPlatform.LINKED_IN]: '领英',
  [SocialPlatform.LOFTER]: 'LOFTER',
  [SocialPlatform.MA_FENG_WO]: '马蜂窝',
  [SocialPlatform.MAI_MAI]: '脉脉',
  [SocialPlatform.MASTONDON]: 'Mastondon',
  [SocialPlatform.MEDIUM]: 'Medium',
  [SocialPlatform.MEET_UP]: 'Meetup',
  [SocialPlatform.MO_MO]: '沫沫',
  [SocialPlatform.ONLY_FANS]: 'Onlyfans',
  [SocialPlatform.PATREON]: 'Patreon',
  [SocialPlatform.PDD]: '拼多多',
  [SocialPlatform.PHONE]: '电话',
  [SocialPlatform.PINTREST]: 'Pintrest',
  [SocialPlatform.POSH_MARK]: 'Poshmark',
  [SocialPlatform.QIN_BAO_BAO]: '亲宝宝',
  [SocialPlatform.QQ]: 'QQ',
  [SocialPlatform.REDDIT]: 'Reddit',
  [SocialPlatform.SIGNAL]: 'Signal',
  [SocialPlatform.SKYPE]: 'Skype',
  [SocialPlatform.SLACK]: 'Slack',
  [SocialPlatform.SNAPCHAT]: 'Snapchat',
  [SocialPlatform.SOUL]: 'Soul',
  [SocialPlatform.SOUND_CLOUD]: 'Soundcloud',
  [SocialPlatform.SPOTIFY]: 'Spotify',
  [SocialPlatform.SUBSTACK]: 'Substack',
  [SocialPlatform.TANG_DOU]: '糖豆',
  [SocialPlatform.TAN_TAN]: '探探',
  [SocialPlatform.TAO_BAO]: '淘宝',
  [SocialPlatform.TELEGRAM]: 'Telegram',
  [SocialPlatform.THREADS]: 'Threads',
  [SocialPlatform.TIKTOK]: 'Tiktok',
  [SocialPlatform.TUMBLR]: 'Tumblr',
  [SocialPlatform.TWITCH]: 'Twitch',
  [SocialPlatform.UNSPLASH]: 'Unsplash',
  [SocialPlatform.VENMO]: 'Venmo',
  [SocialPlatform.VIMEO]: 'Vimeo',
  [SocialPlatform.WE_COM]: '企业微信',
  [SocialPlatform.WEBSITE]: '网址',
  [SocialPlatform.WECHAT]: '微信',
  [SocialPlatform.WEI_BO]: '微博',
  [SocialPlatform.WHATSAPP]: 'WhatsApp',
  [SocialPlatform.X]: 'X(Twitter)',
  [SocialPlatform.XIAN_YU]: '闲鱼',
  [SocialPlatform.XIAO_HONG_SHU]: '小红书',
  [SocialPlatform.XUE_QIU]: '雪球',
  [SocialPlatform.YOUTUBE]: 'Youtube',
  [SocialPlatform.ZHI_HU]: '知乎',
} as const;

export const LIST_SOCIAL_LINKS: SocialLinkItem[] = [
  {
    id: SocialPlatform.ALI_PAY,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.ALI_PAY],
    icon: SocialPlatform.ALI_PAY,
  },
  {
    id: SocialPlatform.ALI_WANG_WANG,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.ALI_WANG_WANG],
    icon: SocialPlatform.ALI_WANG_WANG,
  },
  {
    id: SocialPlatform.AMAZON,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.AMAZON],
    icon: SocialPlatform.AMAZON,
  },
  {
    id: SocialPlatform.APPLE_APP_STORE,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.APPLE_APP_STORE],
    icon: SocialPlatform.APPLE_APP_STORE,
  },
  {
    id: SocialPlatform.APPLE_MUSIC,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.APPLE_MUSIC],
    icon: SocialPlatform.APPLE_MUSIC,
  },
  {
    id: SocialPlatform.APPLE_PODCASTS,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.APPLE_PODCASTS],
    icon: SocialPlatform.APPLE_PODCASTS,
  },
  {
    id: SocialPlatform.ART_STATION,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.ART_STATION],
    icon: SocialPlatform.ART_STATION,
  },
  {
    id: SocialPlatform.BAI_HE,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.BAI_HE],
    icon: SocialPlatform.BAI_HE,
  },
  {
    id: SocialPlatform.BANDCAMP,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.BANDCAMP],
    icon: SocialPlatform.BANDCAMP,
  },
  {
    id: SocialPlatform.BAO_BAO_SHU,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.BAO_BAO_SHU],
    icon: SocialPlatform.BAO_BAO_SHU,
  },
  {
    id: SocialPlatform.BEHANCE,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.BEHANCE],
    icon: SocialPlatform.BEHANCE,
  },
  {
    id: SocialPlatform.BILI_BILI,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.BILI_BILI],
    icon: SocialPlatform.BILI_BILI,
  },
  {
    id: SocialPlatform.BLUE_SKY,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.BLUE_SKY],
    icon: SocialPlatform.BLUE_SKY,
  },
  {
    id: SocialPlatform.BOSS,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.BOSS],
    icon: SocialPlatform.BOSS,
  },
  {
    id: SocialPlatform.CAMEO,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.CAMEO],
    icon: SocialPlatform.CAMEO,
  },
  {
    id: SocialPlatform.CLUB_HOUSE,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.CLUB_HOUSE],
    icon: SocialPlatform.CLUB_HOUSE,
  },
  {
    id: SocialPlatform.DING_TALK,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.DING_TALK],
    icon: SocialPlatform.DING_TALK,
  },
  {
    id: SocialPlatform.DISCORD,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.DISCORD],
    icon: SocialPlatform.DISCORD,
  },
  {
    id: SocialPlatform.DOU_BAN,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.DOU_BAN],
    icon: SocialPlatform.DOU_BAN,
  },
  {
    id: SocialPlatform.DOU_YIN,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.DOU_YIN],
    icon: SocialPlatform.TIKTOK,
  },
  {
    id: SocialPlatform.DRIBBLE,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.DRIBBLE],
    icon: SocialPlatform.DRIBBLE,
  },
  {
    id: SocialPlatform.DROPBOX,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.DROPBOX],
    icon: SocialPlatform.DROPBOX,
  },
  {
    id: SocialPlatform.DUO_LIN_GUO,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.DUO_LIN_GUO],
    icon: SocialPlatform.DUO_LIN_GUO,
  },
  {
    id: SocialPlatform.EMAIL,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.EMAIL],
    icon: SocialPlatform.EMAIL,
  },
  {
    id: SocialPlatform.ESTY,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.ESTY],
    icon: SocialPlatform.ESTY,
  },
  {
    id: SocialPlatform.FACEBOOK,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.FACEBOOK],
    icon: SocialPlatform.FACEBOOK,
  },
  {
    id: SocialPlatform.FEI_SHU,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.FEI_SHU],
    icon: SocialPlatform.FEI_SHU,
  },
  {
    id: SocialPlatform.GITHUB,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.GITHUB],
    icon: SocialPlatform.GITHUB,
  },
  {
    id: SocialPlatform.GITLAB,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.GITLAB],
    icon: SocialPlatform.GITLAB,
  },
  {
    id: SocialPlatform.GOOD_READS,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.GOOD_READS],
    icon: SocialPlatform.GOOD_READS,
  },
  {
    id: SocialPlatform.GOOGLE_PLAY_STORE,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.GOOGLE_PLAY_STORE],
    icon: SocialPlatform.GOOGLE_PLAY_STORE,
  },
  {
    id: SocialPlatform.GOOGLE_PODCAST,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.GOOGLE_PODCAST],
    icon: SocialPlatform.GOOGLE_PODCAST,
  },
  {
    id: SocialPlatform.HU_PU,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.HU_PU],
    icon: SocialPlatform.HU_PU,
  },
  {
    id: SocialPlatform.INSTAGRAM,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.INSTAGRAM],
    icon: SocialPlatform.INSTAGRAM,
  },
  {
    id: SocialPlatform.JD,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.JD],
    icon: SocialPlatform.JD,
  },
  {
    id: SocialPlatform.SHI_JI_JIA_YUAN,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.SHI_JI_JIA_YUAN],
    icon: SocialPlatform.SHI_JI_JIA_YUAN,
  },
  {
    id: SocialPlatform.JUE_JIN,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.JUE_JIN],
    icon: SocialPlatform.JUE_JIN,
  },
  {
    id: SocialPlatform.KICK,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.KICK],
    icon: SocialPlatform.KICK,
  },
  {
    id: SocialPlatform.KUAI_SHOU,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.KUAI_SHOU],
    icon: SocialPlatform.KUAI_SHOU,
  },
  {
    id: SocialPlatform.LA_GOU,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.LA_GOU],
    icon: SocialPlatform.LA_GOU,
  },
  {
    id: SocialPlatform.LAST_FM,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.LAST_FM],
    icon: SocialPlatform.LAST_FM,
  },
  {
    id: SocialPlatform.LINKED_IN,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.LINKED_IN],
    icon: SocialPlatform.LINKED_IN,
  },
  {
    id: SocialPlatform.LOFTER,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.LOFTER],
    icon: SocialPlatform.LOFTER,
  },
  {
    id: SocialPlatform.MA_FENG_WO,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.MA_FENG_WO],
    icon: SocialPlatform.MA_FENG_WO,
  },
  {
    id: SocialPlatform.MAI_MAI,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.MAI_MAI],
    icon: SocialPlatform.MAI_MAI,
  },
  {
    id: SocialPlatform.MASTONDON,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.MASTONDON],
    icon: SocialPlatform.MASTONDON,
  },
  {
    id: SocialPlatform.MEDIUM,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.MEDIUM],
    icon: SocialPlatform.MEDIUM,
  },
  {
    id: SocialPlatform.MEET_UP,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.MEET_UP],
    icon: SocialPlatform.MEET_UP,
  },
  {
    id: SocialPlatform.MO_MO,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.MO_MO],
    icon: SocialPlatform.MO_MO,
  },
  {
    id: SocialPlatform.ONLY_FANS,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.ONLY_FANS],
    icon: SocialPlatform.ONLY_FANS,
  },
  {
    id: SocialPlatform.PATREON,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.PATREON],
    icon: SocialPlatform.PATREON,
  },
  {
    id: SocialPlatform.PDD,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.PDD],
    icon: SocialPlatform.PDD,
  },
  {
    id: SocialPlatform.PHONE,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.PHONE],
    icon: SocialPlatform.PHONE,
  },
  {
    id: SocialPlatform.PINTREST,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.PINTREST],
    icon: SocialPlatform.PINTREST,
  },
  {
    id: SocialPlatform.POSH_MARK,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.POSH_MARK],
    icon: SocialPlatform.POSH_MARK,
  },
  {
    id: SocialPlatform.QIN_BAO_BAO,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.QIN_BAO_BAO],
    icon: SocialPlatform.QIN_BAO_BAO,
  },
  {
    id: SocialPlatform.QQ,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.QQ],
    icon: SocialPlatform.QQ,
  },
  {
    id: SocialPlatform.REDDIT,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.REDDIT],
    icon: SocialPlatform.REDDIT,
  },
  {
    id: SocialPlatform.SIGNAL,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.SIGNAL],
    icon: SocialPlatform.SIGNAL,
  },
  {
    id: SocialPlatform.SKYPE,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.SKYPE],
    icon: SocialPlatform.SKYPE,
  },
  {
    id: SocialPlatform.SLACK,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.SLACK],
    icon: SocialPlatform.SLACK,
  },
  {
    id: SocialPlatform.SNAPCHAT,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.SNAPCHAT],
    icon: SocialPlatform.SNAPCHAT,
  },
  {
    id: SocialPlatform.SOUL,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.SOUL],
    icon: SocialPlatform.SOUL,
  },
  {
    id: SocialPlatform.SOUND_CLOUD,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.SOUND_CLOUD],
    icon: SocialPlatform.SOUND_CLOUD,
  },
  {
    id: SocialPlatform.SPOTIFY,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.SPOTIFY],
    icon: SocialPlatform.SPOTIFY,
  },
  {
    id: SocialPlatform.SUBSTACK,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.SUBSTACK],
    icon: SocialPlatform.SUBSTACK,
  },
  {
    id: SocialPlatform.TANG_DOU,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.TANG_DOU],
    icon: SocialPlatform.TANG_DOU,
  },
  {
    id: SocialPlatform.TAN_TAN,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.TAN_TAN],
    icon: SocialPlatform.TAN_TAN,
  },
  {
    id: SocialPlatform.TAO_BAO,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.TAO_BAO],
    icon: SocialPlatform.TAO_BAO,
  },
  {
    id: SocialPlatform.TELEGRAM,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.TELEGRAM],
    icon: SocialPlatform.TELEGRAM,
  },
  {
    id: SocialPlatform.THREADS,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.THREADS],
    icon: SocialPlatform.THREADS,
  },
  {
    id: SocialPlatform.TIKTOK,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.TIKTOK],
    icon: SocialPlatform.TIKTOK,
  },
  {
    id: SocialPlatform.TUMBLR,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.TUMBLR],
    icon: SocialPlatform.TUMBLR,
  },
  {
    id: SocialPlatform.TWITCH,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.TWITCH],
    icon: SocialPlatform.TWITCH,
  },
  {
    id: SocialPlatform.UNSPLASH,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.UNSPLASH],
    icon: SocialPlatform.UNSPLASH,
  },
  {
    id: SocialPlatform.VENMO,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.VENMO],
    icon: SocialPlatform.VENMO,
  },
  {
    id: SocialPlatform.VIMEO,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.VIMEO],
    icon: SocialPlatform.VIMEO,
  },
  {
    id: SocialPlatform.WE_COM,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.WE_COM],
    icon: SocialPlatform.WE_COM,
  },
  {
    id: SocialPlatform.WEBSITE,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.WEBSITE],
    icon: SocialPlatform.WEBSITE,
  },
  {
    id: SocialPlatform.WECHAT,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.WECHAT],
    icon: SocialPlatform.WECHAT,
  },
  {
    id: SocialPlatform.WEI_BO,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.WEI_BO],
    icon: SocialPlatform.WEI_BO,
  },
  {
    id: SocialPlatform.WHATSAPP,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.WHATSAPP],
    icon: SocialPlatform.WHATSAPP,
  },
  {
    id: SocialPlatform.X,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.X],
    icon: SocialPlatform.X,
  },
  {
    id: SocialPlatform.XIAN_YU,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.XIAN_YU],
    icon: SocialPlatform.XIAN_YU,
  },
  {
    id: SocialPlatform.XIAO_HONG_SHU,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.XIAO_HONG_SHU],
    icon: SocialPlatform.XIAO_HONG_SHU,
  },
  {
    id: SocialPlatform.XUE_QIU,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.XUE_QIU],
    icon: SocialPlatform.XUE_QIU,
  },
  {
    id: SocialPlatform.YOUTUBE,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.YOUTUBE],
    icon: SocialPlatform.YOUTUBE,
  },
  {
    id: SocialPlatform.ZHI_HU,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.ZHI_HU],
    icon: SocialPlatform.ZHI_HU,
  },
];

export const DEFAULT_SOCIAL_LINKS = [
  {
    id: SocialPlatform.WECHAT,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.WECHAT],
    icon: SocialPlatform.WECHAT,
  },
  {
    id: SocialPlatform.QQ,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.QQ],
    icon: SocialPlatform.QQ,
  },
  {
    id: SocialPlatform.DOU_YIN,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.DOU_YIN],
    icon: SocialPlatform.TIKTOK,
  },
  {
    id: SocialPlatform.PHONE,
    name: SOCIAL_LINKS_TEXT[SocialPlatform.PHONE],
    icon: SocialPlatform.PHONE,
  }
];
